---


- hosts: '{{ host }}'


  gather_facts: yes
    
  remote_user: staging
  become: yes 
  become_method: sudo
  vars:
      app_project_path: "/home/projects/micro-services/"
  

  tasks:
    - name: Create App Project Directory
      tags: deploy
      file:
        path: "{{app_project_path}}"
        state: directory
        mode: 0777

    - name: Project Download Script
      shell: | 
        cd /home/projects/micro-services/
        sudo rm -rf Micro-Devops-Tutorial
        git clone https://github.com/safayetjamil647/Micro-Devops-Tutorial.git

    